version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/golang.Dockerfile
    hostname: app
    container_name: ex_app
    ports:
      - "8080:8080"
    networks:
      - eger
    working_dir: /app
    depends_on:
      - jaeger
  jaeger:
    image: jaegertracing/all-in-one
    hostname: jaeger
    container_name: ex_jaeger
    ports:
      - "16686:16686"
      - "14268:14268"
      - "6831:6831/udp"
    expose:
      - 14268
    networks:
      - eger

volumes:
  data:

networks:
  eger: