version: '3.7'

services:
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686"
      - "14268:14268"
      - "6831:6831/udp"
    expose:
      - 14268
    networks:
      - eger

volumes:
  data:

networks:
  eger: